# Generated by Django 4.1.13 on 2024-02-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFurlaxApp', '0002_alter_invoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered')], max_length=50),
        ),
    ]
