# Generated by Django 4.1.13 on 2024-02-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFurlaxApp', '0003_alter_invoice_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
