# Generated by Django 4.1.13 on 2024-02-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFurlaxApp', '0005_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tenure',
            field=models.IntegerField(default=3),
        ),
    ]
